### ISSUE TITLE
Final review - ab2248

### ISSUE THREAD

**Issue by arshibhatnagar** [dwkwvss/orie4741project#11]
This report aims to determine one’s reaction to a block of text. The predictions are to classify a Yelp review as funny, cool, or useful. 

Here are some things I liked about your report:
1.	I love how you parallelized operations to speed up work on large files.  
2.	I liked the visualizations you created for high dimensional spaces by using different techniques, including things we have not learned in class.
3.	I liked how you considered different regularizers and explained why you chose the L2 regularizer.

Things to improve or think about:
1.	You are trying to classify a review as funny, cool, or useful. How do you define these words? For example, funny to a 20 year old is very different from funny to an 60 year old. How do you deal with these differences?
2.	You filter our rows that do not give enough votes. However, doesn’t not having enough votes also indicate how funny or cool the post is? Maybe its lack of votes indicates that the post was boring. You are losing viable information by cutting out data like that. 
3.	You mention facts like you used 100 trees in the random forest. Why did you choose these things? Did you also try out other parameters to see if it helps your results? Your sections on logistic regression, decision trees, and random forests are seem short and lack explanation. It would be great if these parts could be elaborated.

Overall, you posed an interesting question, but I felt your paper lacked detail and explanation. I think you need to spend more time explaining your models and how you evaluated them.

**Comment by dayonenotdaytwo** [comment]
1. Wait funny cool, useful is a category provided for by Yelp. So we don't need to do any defining, since labels are already sort of provided that way

2. if you have less than 10 votes altogether, there is no reason to believe it is not funny over not useful, hence there isn't much data loss there. We're rather not considering those that we are agnostic about.

3. Sure, the 100 trees could have been answered better, but our entire experiment is on bridging the gap between logit regression and unscalable algorithms using text embeddings, so we did not necessarily need to explain the algorithms.

4. Wait what. We clearly mentioned that this is the cross-validation score. We pretty clearly mentioned this.

I feel like you didn't really read ours properly before giving comments, and don't really reflect our actual content

**Comment by pinnnnnn** [comment]
My teammate has already explained what you proposed in your "comment(?)". It's pretty clear that you didn't read our report properly.

Seriously, we spent hours and hours to do this project. It would be nice if you could spend maybe a little bit more time reading our report carefully before you write. 

Merry Christmas

**Comment by arshibhatnagar** [comment]
I did read your paper and yes I agree with your disagreement on comment 4. I have updated your review to take this into account. However, I still stand by my first 3 comments. They are just my opinion, which you can disagree on. I did read your paper carefully and those are the comments I had. Please do not claim I did not read the paper carefully just because you disagree with my comments.

**Comment by dayonenotdaytwo** [comment]
Apologies. You seemed to be missing some key details that we put in. Pinn's probably pretty stressed. I merely wished to address that your points may be already answered in the paper. Negative comments are fine but we wanted to make sure it was well-informed. 

Have a good break.

**Comment by TheButlah** [comment]
1. Defining what makes a review as funny cool or useful is done by the users of yelp, because they are labels generated by the users. This was stated in our report.

2. The lack of responses could mean that the post was boring, or just got unlucky and never reached a good number of people to view it. Because of this ambiguity we filtered out those responses and only wanted to look at the reviews that garnered many responses, as these definitely fell into those three categories we were given. We don't lose any valuable information because we don't have tags for "boring" reviews. To us, those reviews are essentially noise that we can filter out.

3. Those sections are short because the point of our paper is to go from unscalable algorithms like random forest and decision trees to scalable algorithms like logistic regression and SVMs by engineering an embedding space for the reviews. Hence, we allotted more of our paper to explaining the things that were important. The models were not the point of the paper, the embeddings were.

Hopefully that clarifies some of the issues you had!
