### ISSUE TITLE
Midterm Review(sz244)

### ISSUE THREAD

**Issue by sz244** [dwkwvss/orie4741project#8]
The goal of the project is to predict the usefulness,coolness and funniness of Yelp Reviews.

Here's a few thing I like about this project

1. I like that you produce a lot of visualization so that we can get a more straightforward grasp of your the data distribution.

2. It's good that your try to understand the word2vec embedding instead of using it directly like a black box.

Here's a few concerns/questions/suggestions:

1. Are you using pre-trained word2vec embedding or do you train it on your review data?
- If so, what the vocabulary size of your corpus? You may consider using a embedding with much less dimensions if the vocabulary size is moderate.
- If not I think it might be helpful to use pre-trained embedding since the review data set seem a bit small. 

3. It's not exactly clear what are your input features and how are you trying to deal with review with varying length(besides the LSTM model). Are you planning to sum up all the word2ve vectors, take take the first x words in review and concat?

2. Maybe some sentiment analysis can be useful. Also you may consider looking at doc2vec. https://radimrehurek.com/gensim/models/doc2vec.html

**Comment by dayonenotdaytwo** [comment]
Thank you for your suggestions! As for your first question, we are training our own word2vec model, since we believe the architecture ideal for this analysis may not be generalizable from commonly available word2vec formulations. As for the smallness of the dataset, we actually have 4 million reviews with at least 300 words each, so we may train our word2vec on the entire dataset first and apply it to the subset we are focusing on. We will definitely look into doc2vec. Our focus though, is not necessarily primarily on text-to-numeric embeddings, although it's a very significant portion. It may be more heavily focused on dimensionality reduction techniques like PCA, kernel-PCA, and autoencoders, and classification algorithms at this stage, since those will be challenging enough. 

Thanks again for your comments!
